---
Comment.date_time_format: M d, Y
Comment.feed_limit: 10
Comment.level: 1
Hook.bootstraps: tinymce,full_calendar
Meta.description: Blabfeed, a digital solution, for the real world
Meta.generator: 'Croogo - Content Management System'
Meta.keywords: >
    Blabfeed, digital signage, Omaha, Nebraska, DOOH, Digital
    out of home, network, advertising
Meta.robots: index, follow
Reading.date_time_format: D, M d Y H:i:s
Reading.nodes_per_page: 5
Service.akismet_key: your-key
Service.akismet_url: http://your-blog.com
Service.recaptcha_private_key: your-private-key
Service.recaptcha_public_key: your-public-key
Site.email: derek@blabfeed.com
Site.feed_url: 
Site.locale: eng
Site.promoted: 1
Site.status: 1
Site.tagline: a blabfeed solution.
Site.theme: 
Site.timezone: 0
Site.title: blabfeed beta 1.0
Writing.wysiwyg: 1
